[#ftl]
[#-- @implicitly included --]
[#-- @ftlvariable name="tickets" type="java.util.Collection<gr.uoa.di.entities.Ticket>" --]
[#-- @ftlvariable name="pageName" type="java.lang.String" --]
[#-- @ftlvariable name="parent" type="gr.uoa.di.entities.ParentMetadata" --]
[#-- @ftlvariable name="ticket" type="gr.uoa.di.entities.Ticket" file="templates/receipt/receipt.ftl" --]
[#-- @ftlvariable name="result" type="java.lang.String" file="templates/admin/search_user.ftl" --]
[#-- @ftlvariable name="userList" type="java.util.Collection<User>" --]
[#-- @ftlvariable name="providerList" type="java.util.Collection<ProviderMetadata>" file="templates/admin/statistics.ftl" --]
[#-- @ftlvariable name="message" type="java.lang.String" --]
[#-- @ftlvariable name="error" type="java.lang.String" --]
[#-- @ftlvariable name="taxOffices" type="java.util.Collection<TaxOffice>" file="templates/auth/register_provider.ftl" --]
[#-- @ftlvariable name="registerForm" type="gr.uoa.di.forms.auth.ProviderRegisterForm" file="templates/auth/register_provider.ftl" --]
[#-- @ftlvariable name="event" type="gr.uoa.di.entities.Event" --]
[#-- @ftlvariable name="user" type="gr.uoa.di.entities.User" --]
[#-- @ftlvariable name="provider" type="gr.uoa.di.entities.ProviderMetadata" --]
[#-- @ftlvariable name="events" type="java.util.Collection<Event>" --]
[#-- @ftlvariable name="attributes" type="java.util.Collection<HomeController.Info>" file="templates/index.ftl" --]
[#-- @ftlvariable name="currentUser" type="gr.uoa.di.entities.User" --]
